### ISSUE TITLE
list wording

### ISSUE THREAD

**Issue by bvogel** [micke/valid_email2#205]
I'm aware this would be a breaking change, but please consider moving lists to the now widely accepted naming convention of `allow_list` and `deny_list` and probably while at it move the default branch to `main` as is the standard for new projects?

**Comment by ianbayne** [comment]
Hi @micke, I'd be interested in taking a stab at this. Would you prefer outright replacements for the relevant methods etc (`blacklist` -> `deny_list`, etc.), use of aliases, or deprecation (perhaps using `Gem::Deprecate` so we can inform the developer when support will be removed)?

**Comment by micke** [comment]
@ianbayne i would really appreciate it! What do you think about both aliasing and issuing deprecation warning when the old naming scheme is used? Then we can cut a minor release where users can start using the new naming scheme :)

**Comment by ianbayne** [comment]
Sure, sounds good to me, @micke.

If I'm understanding correctly, the more public interface for your gem seems to be through validations by means of `EmailValidator`, and so those options (`options[:blacklist]` etc) definitely need to be aliased and deprecated. Do the underlying class and instance methods in `ValidEmail2` and `Address` also need the same treatment? 

I guess the average user is probably only accessing `ValidEmail2.blacklist` and `Address#whitelisted?` etc through that public interface during validations, but perhaps it still makes sense to alias and deprecate the relevant methods in `ValidEmail2` and `Address` too since we don't know how all users are making use of your gem...?
