### ISSUE TITLE
`valid_mx?` behaviour change following the new `null_mx` handling

### ISSUE THREAD

**Issue by tom-lord** [micke/valid_email2#208]
Following [this change](https://github.com/micke/valid_email2/pull/207/files#diff-0e2e718f89af40f6a3719f700298845f3eeb841705f70b6272ddd387b2d9e705R94)

Suppose a domain has an `A` server.
If it has _no `MX` servers_, then `ValidEmail2::Address#valid_mx?` method returns `true`. But if it has a null `MX` server then the method returns `false`.
For instance:

```
ValidEmail2::Address.new('test@example.com').valid_mx?
```

Returns `true` in version `< 5` of this library, and `false` in version `5.0`.

Is that expected behaviour? Or should the (non-strict) `valid_mx?` method still return `true` here?

**Comment by micke** [comment]
Hi. Yes, this is the expected outcome as i understand it, have you looked at https://github.com/micke/valid_email2/issues/206 and the RFC?

Null MX is a feature where the owner of the domain can explicitly disable the implicit use of the `A` record as a `MX` server.

I released it as a major version release to adhere to semver so that users upgrading would read the release notes where the issue/pr i linked.
