### ISSUE TITLE
vendor location (or name clarity)

### ISSUE THREAD

**Issue by kenn** [micke/valid_email2#60]
I have `blacklist.yml` under `vendor`, but this feels strange, because `vendor` directory is a global namespace and should be well organized. I can't even tell `blacklist.yml` is for this gem (and email) until I actually open the file.

I see two options.

- Rename the file to `vendor/blacklist(ed)_emails.yml` (more consistent naming with `disposable_emails.yml`)
- Move both files under `vendor/valid_email2/*`

This gem is awesome, I'm glad I finally found something I like! 👍

**Comment by lisinge** [comment]
I agree with you, it would be a lot better to be more consistent with `disposable_emails.yml`.

The problem is that we can't really change the name without releasing another major update of the gem as the gem is following semantic versioning. And if we change the name on the file we will break peoples apps who are expecting it to be named `blacklist.yml`.

The blacklist feature was contributed in PR #5 so i know that someones code will break at least.

One solution would be to make both files path configurable, and make them default to the current naming scheme. For example `ValidEmail2.disposable_emails_path = ...`.  
This won't force us to release a new major version either. PRs are appreciated 👍 

Thanks, i'm glad you like the gem 😃

**Comment by micke** [comment]
I've changed the directory and naming scheme in v3 of the gem. Read more here https://github.com/micke/valid_email2/blob/master/CHANGELOG.md#version-300
